export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USER = "GET_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

export const GET_ALL_STUDENTS = "GET_ALL_STUDENTS";
export const GET_STUDENT = "GET_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT ";
export const GET_STUDENTS_BY_PARENTS = "GET_STUDENTS_BY_PARENTS";

export const GET_ALL_PARENTS = "GET_ALL_PARENTS";
export const GET_PARENT = "GET_PARENT";
export const UPDATE_PARENT = "UPDATE_PARENT";
export const DELETE_PARENT = "DELETE_PARENT";
export const PARENT_NOT_FOUND = "PARENT_NOT_FOUND";
export const GET_PARENT_ID = "GET_PARENT_ID";
export const REGISTER_PARENT = "REGISTER_PARENT";

export const SET_USER_ACTIVE = "SET_USER_ACTIVE";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_ALL_ADMINS = "GET_ALL_ADMINS";
export const GET_ADMIN_BY_ID = "GET_ADMIN_BY_ID";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const GET_ADMIN_BY_NAME = "GET_ADMIN_BY_NAME";
export const GET_ADMIN_BY_EMAIL = "GET_ADMIN_BY_EMAIL";
export const BAN_ADMIN = "BAN_ADMIN";
export const RESTORE_ADMIN = "RESTORE_ADMIN";
export const FILTER_BY_STATE = "FILTER_BY_STATE";

export const GET_ALL_GRADES = "GET_ALL_GRADES";
export const GET_GRADE_BY_ID = "GET_GRADE_BY_ID";
export const UPDATE_GRADE = "UPDATE_GRADE";
export const REMOVE_GRADE = "REMOVE_GRADE";
export const FILTER_BY_STATE_GRADE = "FILTER_BY_STATE_GRADE";
export const POST_GRADE = "POST_GRADE";

export const GET_VALORACION = "GET_VALORACION";
export const POST_VALORACION = "POST_VALORACION";
export const EDIT_VALORACION = "EDIT_VALORACION";
export const GET_HAS_RATED = "GET_HAS_RATED";
export const SAVE_COMENTARIO_ID = "SAVE_COMENTARIO_ID";
